---
- name: install PyMySQL
  pip3: name=PyMySQL state=present
  
- name: Create the database
  mysql_db: name=test-rep login_user="{{root_db}}" login_password="{{login_password_db}}"  state=present 
  
- name: Create the replication users 
  mysql_user: 
    login_user: "{{root_db}}" 
    login_password: "{{login_password_db}}"  
    name: replication 
    host: "%" 
    password: * 
    priv: "*.*:REPLICATION SLAVE"
    state: present 

- name: Get the current master servers replication status 
  mysql_replication: 
    login_user: "{{root_db}}" 
    login_password: "{{login_password_db}}" 
    mode: getprimary
  register: information

- name: show the status 
  debug: 
    var: information

- name: Creates directory
  file:
    path: "{{db_backup}}"
    mode: 0775
    state: directory

- name: Prepare the script
  copy: 
    src: "{{script_path}}"
    dest: "{{db_backup}}"
  
- name: Execute the script
  command: sh /var/backup/db/script.sh