---
# tasks file for django

# - name: Creates directory
#   file: "path=/home/{{project_name}} state=directory"

# - name: install packages
#   yum: "name=python-virtualenv state=present" 

#  - name: create virtualenv and install django in it
#    pip: "name=django virtualenv=/home/{{project_name}}/env virtualenv_command=virtualenv"

# - name: install a django project
#   command: "/home/{{project_name}}/env/bin/django-admin.py startproject {{project_name}} chdir=/home/{{project_name}}/"  

# - name: install gunicorn
#   pip: "name = gunicorn /home/{{project_name}}/env/bin/ chdir=/home/{{project_name}}""


# - name: chanage settings.py 
#   lineinfile:
#     path: /home/{{project_name}}/{{project_name}}/{{project_name}}/settings.py 
#     line: ALLOWED_HOSTS = ['*']

# - name: setup gunicorn.service
#   copy:
#     src: "{{path_gunicorn}}"
#     dest: "{{dest_gunicorn}}"

- name:
  template:
    src: "{{src_https_server_conf}}"
    dest: "{{dest_nginx}}"
  notify:
    - Restart nginx


